### PR TITLE
Added resources page.

### PR DESCRIPTION
**Pull request by Scetch**
### What are you trying to accomplish?
Added a CS Resources page where things such as cheat sheets, documentation, online judges and problems can be posted for students to reference.

### How are you accomplishing it?
Added a new markdown page and modified the main application template.

### Is there anything reviewers should know?
No

- [x] Is it safe to rollback this change if anything goes wrong?

### CODE REVIEW

**Comment by HarshdipD** [comment]
Looks good

**Comment by HarshdipD** [comment]
Pls merge this

**Comment by Scetch** [comment]
We haven't merged this because we haven't decided if we want a singular page for all resources (internships, courses, etc). The final say in how we do this will be from @EricPickup. If he wants it we will merge, if not I'll take all this information and put it in the other page.

**Comment by EricPickup** [comment]
@Scetch for now let's just distribute it onto the other page (I think some of this is already on there) and we can decide further down the road if we want to split into separate pages if it starts getting too big/messy

**Comment by Scetch** [comment]
@EricPickup Added a Resources section in the main Guide page with this information. Removed all previous changes.

**Comment by shli3** [comment]
I feel like it should be named something other than resources, only because the dropdown menu no the top bar is already named resources, having resources within resources seems redundant

**Pull request merged**
